apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: logging
spec:
  containers:
  - image: busybox
    name: busybox
    command: [ "sleep", "3600" ]
    resources:
      requests:
        memory: "128Mi"
        cpu: "40m"
        ephemeral-storage: "5Mi"
      limits:
        memory: "128Mi"
        cpu: "40m"
        ephemeral-storage: "5Mi"
    env:
    - name: cluster
      value: cluster01
    - name: project
      value: project01
