FROM debian:stretch as builder
COPY --from=amd64/busybox:1.31.0 /bin/busybox /bin/busybox
RUN chmod 555 /bin/busybox \
 && /bin/busybox --install

FROM  registry.cn-shanghai.aliyuncs.com/digk8s/fluent-bit:1.2.0-3
COPY --from=builder /bin/ /bin/
